import localFont from "next/font/local";
import Link from "next/link";
import styles from "./styles/layout.module.css";
import { CartProvider } from "@/context/CartContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div>
          <nav className={styles.navbar}>
            <a href="https://myside.com.br/" target="_blank" className={styles.logo}>
              <img
                src="https://myside.com.br/public-web/assets/logos/myside-logo.svg"
                className="h-8"
                alt="MySideLogo"
              />
            </a>
            <ul className={styles.navList}>
              <li className={styles.navItem}>
                <Link href="/" passHref>
                  Home
                </Link>
              </li>
              <li className={styles.navItem}>
                <Link href="/products">Produtos</Link>
              </li>
              <li className={styles.navItem}>
                <Link
                  href="https://www.linkedin.com/in/vitor-perraro-rosa-283686238/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Desenvolvedor
                </Link>
              </li>
            </ul>
          </nav>
          <hr />
        </div>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
};

export default RootLayout;
